name: Build & Push Docker Image to ACR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Azure login
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Get short SHA for tagging
      - name: Get short SHA
        run: echo "SHORT_SHA=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV

      # Step 4: Build & push with ACR Build Action
      - name: Build and Push Docker Image
        uses: azure/acr-build@v1
        with:
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          resource-group: rg-acr-dev
          registry: newrgacdev
          image: pwc-tax-data-api:v-${{ env.SHORT_SHA }}
          push: true
          platform: linux/amd64,linux/arm64
