name: Build & Push Docker Image to Private ACR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository with minimal history
    - name: Checkout code
      uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 1

    - name: Configure Azure credentials
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3.10.0

    - name: Verify ACR
      run: |
        az account show
        az acr list -o table

    - name: Login to Azure ACR
      run: |
        az acr login --name newrgacdev
        
    - name: Get short SHA
      id: sha
      run: echo "SHORT_SHA=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV

    - name: Build and deploy Container App for API
      uses: azure/contianer-apps-deploy-action@v2
      with:
        app-name: pwc-tax-data-api
        resource-group: rg-acr-dev
        registry-server: ${{ env.ACR_LOGIN_SERVER }}
        repository: pwc-tax-data-api
        image-tag: ${{ env.SHORT_SHA }}