name: Build & Push Docker Image to Private ACR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository with minimal history
    - name: Checkout code
      uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 1

    - name: Configure Azure credentials
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3.10.0

    - name: Verify ACR
      run: |
        az account show
        az acr list -o table
        
    - name: Get short SHA
      id: sha
      run: echo "SHORT_SHA=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV

    # ðŸ”¹ BUILD + PUSH
    - name: Build & Push Image (ACR Task)
      run: |
        az acr build \
          --registry newrgacdev \
          --image pwc-tax-data-api:${{ env.SHORT_SHA }} \
          .