name: Build & Push Docker Image to Private ACR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    # Step 1: Checkout the repository with minimal history
    - name: Checkout code
      uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 1

    # # creation of docker builder

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: linux/amd64,linux/arm64  

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: docker-container

    - name: Configure Azure credentials
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Verify ACR
      run: |
        az account show
        az acr list -o table
        
    - name: Show runner public IP
      run: |
        echo "Public IP address:"
        curl -s https://api.ipify.org
        echo ""

    - uses: azure/docker-login@v2
      with:
        login-server: newrgacdev.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Get short SHA
      id: sha
      run: echo "SHORT_SHA=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV

    - name: Build in ACR
      run: |
        az acr build \
          --registry newrgacdev.azurecr.io \
          --image pwc-tax-data-api:v-${{ env.SHORT_SHA }} \
          --image pwc-tax-data-api:latest \
          .
